# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73eb006f18f245b9f1121be83df78f9844e08da39092544a7480d7b2b073ef06ec8eb055d2236376d9e9a141f3381bbf23947ae524e6b31b84c4bbf9d4438eb1

test:
  secret_key_base: 359835dc12948c4d17e05b381e61715f21981e9eaf2ed90faa114516ab6d59b4dfe816bd9135f519af5528219f53c5ecd228bdccd705ce40916349e92b97a29d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
